[package]
name = "minosrus_lang"
version = "0.1.0"
authors = ["Tix3Dev"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
